<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyName>Ensemble</AssemblyName>
    <CopyToMuseDash Condition="'$(CopyToMuseDash)' == ''">false</CopyToMuseDash>
  </PropertyGroup>

  <Target Name="CopyDLLs" AfterTargets="Build" Condition="'$(CopyToMuseDash)' == 'true'">
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(MD_NET6_DIRECTORY)\Mods" />
    <Copy SourceFiles="$(TargetDir)MDEN.Protocol.dll" DestinationFolder="$(MD_NET6_DIRECTORY)\UserLibs" />
    <Message Text="Copied DLL -&gt; $(MD_NET6_DIRECTORY)\Mods\$(AssemblyName).dll" Importance="High" />
  </Target>

  <ItemGroup>
    <Compile Remove="Assets\Stickers\Pack1\**" />
    <EmbeddedResource Remove="Assets\Stickers\Pack1\**" />
    <None Remove="Assets\Stickers\Pack1\**" />
    <Compile Remove="inspect_cs\**" />
    <EmbeddedResource Remove="inspect_cs\**" />
    <None Remove="inspect_cs\**" />
    <Compile Remove="MDEN.Protocol\**" />
    <EmbeddedResource Remove="MDEN.Protocol\**" />
    <None Remove="MDEN.Protocol\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*.png" />
    <EmbeddedResource Include="Assets\**\*.wav" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\net6\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="CustomAlbums">
      <HintPath>$(MD_NET6_DIRECTORY)\Mods\CustomAlbums.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppDOTween">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2CppDOTween.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppNewtonsoft.Json">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2CppNewtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPeroTools2.Account">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2CppPeroTools2.Account.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPeroTools2.Resources">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2CppPeroTools2.Resources.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSirenix.Serialization">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2CppSirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
    </Reference>
    <Reference Include="LocalizeLib">
      <HintPath>$(MD_NET6_DIRECTORY)\Mods\LocalizeLib.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\cpp2il_out\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="PopupLib">
      <HintPath>$(MD_NET6_DIRECTORY)\Mods\PopupLib.dll</HintPath>
    </Reference>
    <Reference Include="Tomlet">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\net6\Tomlet.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>$(MD_NET6_DIRECTORY)\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="MDEN.Protocol\MDEN.Protocol.csproj" />
  </ItemGroup>

</Project>
